[package]
name = "nightcycle/cold-fusion"
description = "A framework inspired by Elttob's Fusion allowing for chained states and explicit memory management"
license = "MIT"
authors = ["Elttob", "Nightcycle"]
version = "2.1.5"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Math = "nightcycle/math@3.6.0"
Signal = "nightcycle/signal@^1.0.0"
Maid = "nightcycle/maid@^1.0.2"

