[package]
name = "nightcycle/cold-fusion"
description = "A modded version of Elttob's Fusion focused on general OOP usage across server and client"
license = "MIT"
authors = ["Elttob", "Nightcycle"]
version = "1.1.2"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "quenty/signal@2.0.0-canary"
maid = "quenty/maid@2.0.1-canary"
