[package]
name = "nightcycle/cold-fusion"
description = "A framework inspired by Elttob's Fusion allowing for chained states and explicit memory management"
license = "MIT"
authors = ["Elttob", "Nightcycle"]
version = "2.1.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Math = "nightcycle/math@3.6.0"
Signal = "quenty/signal@2.0.0-canary"
Maid = "quenty/maid@2.0.1-canary"
