[package]
name = "nightcycle/cold-fusion"
description = "A framework inspired by Elttob's Fusion allowing for chained states and explicit memory management"
license = "MIT"
authors = ["Elttob", "Nightcycle"]
version = "2.0.20"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
math = "nightcycle/math@3.4.0"
signal = "quenty/signal@2.0.0-canary"
maid = "quenty/maid@2.0.1-canary"
